GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDg4OTU0fQ.0QBEDsOekr9FoZgBd_fIxTJLIC9g2r5OKrWi0R-ENN4

###

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDg4OTU0fQ.0QBEDsOekr9FoZgBd_fIxTJLIC9g2r5OKrWi0R-ENN4

###

POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDg4OTU0fQ.0QBEDsOekr9FoZgBd_fIxTJLIC9g2r5OKrWi0R-ENN4
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDg4OTU0fQ.0QBEDsOekr9FoZgBd_fIxTJLIC9g2r5OKrWi0R-ENN4

###

DELETE http://localhost:3000/districts/332/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDg4OTU0fQ.0QBEDsOekr9FoZgBd_fIxTJLIC9g2r5OKrWi0R-ENN4

###

PUT http://localhost:3000/districts/332/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDg4OTU0fQ.0QBEDsOekr9FoZgBd_fIxTJLIC9g2r5OKrWi0R-ENN4
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/states/3/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDg4OTU0fQ.0QBEDsOekr9FoZgBd_fIxTJLIC9g2r5OKrWi0R-ENN4
